ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ ENV }}.neeli.online
CATALOGUE_HOST: catalogue-{{ ENV }}.neeli.online
REDIS_HOST: redis-{{ ENV }}.neeli.online
USER_HOST: user-{{ ENV }}.neeli.online
CART_HOST: cart-{{ ENV }}.neeli.online
MYSQL_HOST: mysql-{{ ENV }}.neeli.online
SHIPPING_HOST: shipping-{{ ENV }}.neeli.online
RABBITMQ_HOST: rabbitmq-{{ ENV }}.neeli.online
PAYMENT_HOST: payment-{{ ENV }}.neeli.online
FRONTEND_HOST: frontend-{{ ENV }}.neeli.online