- name: App setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: Systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: Start user
  ansible.builtin.service:
    name: user
    state: restarted
    enabled: yes