# ansible-playbook -e component=$COMPONENT -e ENV=$ENV ansible-roles-roboshop.yaml
# ENV is coming from bootstrap.sh file from 40-dabases module
MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop-mysql-{{ ENV }}/mysql_root_password', region='us-east-1') }}"