- name: Copy {{ component }} service and dynamically update placeholders
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: Restart {{ component }}

- name: Daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true